### ISSUE TITLE
change sha2 to sha256 

### ISSUE THREAD

**Issue by Domiroh** [hsasctf/lxctf#35]
Following configs should be changed:

roles/vpn/templates/openssl/server.cnf.j2:5:  `default_md = sha2`
roles/vpn/templates/openssl/client1.cnf.j2:5:  `default_md = sha2`

to

`default_md = sha256`

This solved an error while running the ansible provision.

**Comment by antfeh** [comment]
Should be fixed with [this pull request](https://github.com/hsasctf/lxctf/pull/38).

**Comment by c-goes** [comment]
Not sure if this changes anything as sha256 is one of 3 algorithms included in sha2. But doesn’t hurt of course. Thanks

**Comment by antfeh** [comment]
We are not testing anymore. This is done on physical host with ubuntu 18.04, 4.15.0-72-generic, OpenSSL 1.1.1, with and zfs partition for the containers. The fix worked for this environment.

**Comment by c-goes** [comment]
Never tried 18.04 because of LXD api errors with ansible. I will need to add it to travis before merge

**Comment by c-goes** [comment]
Maybe it works on 18.04 just because it uses the same LXD version as 16.04 with xenial-backports. Good to know this.
