### ISSUE TITLE
Release 0.1.2-alpha

### ISSUE THREAD

**Issue by antfeh** [hsasctf/lxctf#39]
@c-goes our ctf is planned for january and we would like to have the ctf up and running for testing and usage. Is it possible to get a release until sunday evening 15.12.2019 23:59?
We will add pull requests for all features we woud like in the release until tomorrow evening.

**Comment by c-goes** [comment]
A release that works in the development env is probably possible but I don’t have the time to test other host operating systems than 16.04

**Comment by c-goes** [comment]
@antfeh all PRs added now?

**Comment by antfeh** [comment]
Sorry for not reacting. Indeed all branches were added. Thanks a lot for your work!
