### ISSUE TITLE
Registration/Webserver

### ISSUE THREAD

**Issue by xiao-pi** [hsasctf/lxctf#41]
We wanted to know if there is a similar python file like demo.py which is for app_registration? Or do we need to start it manually? And if so can you give us some pointer?

Do we need to start it manually with waitress or ???

Another point that you still can access the Website https://ctf.uber.space. We are wondering where is the location, is this the old server from the previous ctf.

**Comment by c-goes** [comment]
1. there is the register_tornado.py path is already adapted in firewall branch 
2. This is just a Webspace that I was using for registration last time. You can have the db from it for all existing teams.

**Comment by c-goes** [comment]
it's now (17756e9) automatically started via supervisord and reachable via default ip port 80
