### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by xiao-pi** [hsasctf/lxctf#51]
Hi I started the register_tornado.py and than I get this Error.

"Database error, there is no empty event in database (event without ticks)"

I tried to reset the Database with the manage_reset_db.py and there I get the Error.

"Can't connect to MySQL server on 127.0.0.1" but the connection is there

Where is our problem?

**Comment by c-goes** [comment]
the message tells you to add a new event to the database. It can be done via http://10.38.1.1/admin when you also start the tornado_file.py

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiao-pi** [comment]
ok thx. I try!

**Comment by c-goes** [comment]
I edited the URL because it was wrong. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
